name: 'coblocks'

config-version: 2
version: '0.1'

profile: 'coblocks'

model-paths: ["blocks"]
seed-paths: ["seeds"]

target-path: "target"

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  coblocks:
    +materialized: table
    staging:
      +materialized: view
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
